# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/Courses/CA/Proje/Faze 2/Project-phase-2/divisor/project_1/project_1.cache/wt} [current_project]
set_property parent.project_path {E:/Courses/CA/Proje/Faze 2/Project-phase-2/divisor/project_1/project_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {{E:/Courses/CA/Proje/Faze 2/Project-phase-2/divisor/division.vhd}}
synth_design -top division -part xc7vx485tffg1157-1
write_checkpoint -noxdef division.dcp
catch { report_utilization -file division_utilization_synth.rpt -pb division_utilization_synth.pb }
